version: '3.7'

services:

  task-frontend:
    container_name: task-frontend
    image: mohamedsaberfcih/stc-task-frontend:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4200:4200
